sudo: false
dist: trusty

group: edge

language: php
php:
  - '7.2'

services:
  - docker

env:
  - DB_SERVER=mysql:5.7
  - DB_SERVER=mariadb:10.2

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - cd tests
  - docker-compose up -d ximdex

script:
  - docker-compose run test
  
notifications:
  email:
    recipients:
      - travis@ximdex.com
    on_success: change
    on_failure: always
    
  slack:
    rooms:
      - ximdexteam:tJAT66V6VSJeHR3H2CDCImnK#ximdex