<?php
/**
 * Created by PhpStorm.
 * User: jvargas
 * Date: 14/02/17
 * Time: 18:24
 */

namespace Ximdex\API;



use Illuminate\Http\JsonResponse;

class APIResponse  extends JsonResponse {
    const ERROR = -1;
    const OK = 0;

    private $attrs = [];

    public function __construct($headers = [], $status = 200, $options = 0) {
        parent::__construct( null, $status, $headers, $options );
        $this->attrs = [
            'status' => self::OK,
            'message' => '',
            'response' => [],
        ];
    }

    /**
     * Sets the status code
     *
     * @param $status
     * @return $this
     */
    public function setStatus($status){
        $this->attrs['status'] = $status;
        return $this;
    }

    /**
     * Sets the message
     *
     * @param $message
     * @return $this
     */
    public function setMessage($message){
        $this->attrs['message'] = $message;
        return $this;
    }

    /**
     * Sets the response
     *
     * @param $response
     * @return $this
     */
    public function setResponse($response){
        $this->attrs['response'] = $response;
        return $this;
    }

    public function sendContent() {
        $this->setData($this->attrs);
        return parent::sendContent(); // TODO: Change the autogenerated stub
    }
}